version: '3.8'
services: 
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: "secret"
    ports: 
      - '5432:5432'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'